name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # hoặc 'master' nếu bạn dùng branch này

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cài Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cài Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy lên Firebase
        run: firebase deploy --only hosting --project testlabstest-d0ef0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
